---

- name: Configure Redis
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^bind ', line: 'bind 30.0.0.1' }
    - { regexp: '^#? ?requirepass ', line: "requirepass {{ redis_password }}" }
  notify: restart redis

- name: Ensure Redis is started
  service:
    name: redis-server
    state: started
    enabled: yes

