---
container_ips:
  haproxy:
    - { dev: 'eth1', ip: '20.0.0.1/24' }
  waf1:
    - { dev: 'eth0', ip: '20.0.0.2/24' }
    - { dev: 'eth1', ip: '192.168.1.1/24' }
  waf2:
    - { dev: 'eth0', ip: '20.0.0.3/24' }
    - { dev: 'eth1', ip: '192.168.1.2/24' }
  web1:
    - { dev: 'eth0', ip: '192.168.1.3/24' }
    - { dev: 'eth1', ip: '30.0.0.3/24' }
  web2:
    - { dev: 'eth0', ip: '192.168.1.4/24' }
    - { dev: 'eth1', ip: '30.0.0.4/24' }
  web3:
    - { dev: 'eth0', ip: '192.168.1.5/24' }
    - { dev: 'eth1', ip: '30.0.0.5/24' }
  redis:
    - { dev: 'eth0', ip: '30.0.0.1/24' }

container_routes:
  web1:
    - { gw: '192.168.1.1', dev: 'eth0' }
  web2:
    - { gw: '192.168.1.1', dev: 'eth0' }
  web3:
    - { gw: '192.168.1.2', dev: 'eth0' }

redis_password: "{{ lookup('password', '/tmp/redis_pass chars=ascii_letters,digits length=24') }}"
